services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - $MYSQLDB_PORT:$MYSQLDB_PORT
    restart: unless-stopped
    environment:
      MYSQL_ROOT_USER: $MYSQLDB_USER
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
    volumes:
      - mysql-volume:/var/lib/mysql:rw
      - ./mysql-db/init:/docker-entrypoint-initdb.d/

  api:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    restart: unless-stopped
    depends_on:
      - mysqldb
    # condition: service_healthy

volumes:
  mysql-volume:
