services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - '3306:3306'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-volume:/var/lib/mysql:rw
      - ./mysql-db/init:/docker-entrypoint-initdb.d/

  api:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    restart: unless-stopped
    depends_on:
      - mysqldb
    # condition: service_healthy

volumes:
  mysql-volume:
